import { existsSync } from 'fs';
import https from 'https';
import { delimiter, join } from 'path';
import puppeteer, { Browser } from 'puppeteer-core';

interface TranscriptLine {
  text: string;
  start: number;
  dur: number;
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface AdChapter {
  title: string;
  startMs: number;
  endMs: number;
}

export interface VideoMetadata {
  title: string;
  author: string;
  subscriberCount: string;
  viewCount: string;
  publishDate: string;
}

interface PageData {
  availableLanguages: CaptionTrack[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
}

interface TranscriptSegment {
  timestamp: string;
  text: string;
}

const REQUEST_TIMEOUT = 30000;
const WATCH_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';
const CHROME_COMMAND_CANDIDATES = ['google-chrome', 'google-chrome-stable', 'chromium-browser', 'chromium', 'chrome', 'chrome.exe'];

let browserPromise: Promise<Browser> | null = null;

function uniqueLanguageCodes(tracks: CaptionTrack[]): CaptionTrack[] {
  const seen = new Set<string>();
  return tracks.filter((track) => {
    const key = `${track.languageCode}:${track.isAutoGenerated}`;
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
}

function getChromeCandidates(): string[] {
  const pathCandidates = (process.env.PATH ?? '')
    .split(delimiter)
    .filter(Boolean)
    .flatMap((directory) => CHROME_COMMAND_CANDIDATES.map((command) => join(directory, command)));

  const macCandidates = [
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Chromium.app/Contents/MacOS/Chromium'
  ];

  const windowsBasePaths = [
    process.env.LOCALAPPDATA,
    process.env.PROGRAMFILES,
    process.env['PROGRAMFILES(X86)']
  ].filter((value): value is string => Boolean(value));

  const windowsCandidates = windowsBasePaths.map((basePath) => join(basePath, 'Google', 'Chrome', 'Application', 'chrome.exe'));

  return [...new Set([
    process.env.PUPPETEER_EXECUTABLE_PATH,
    process.env.CHROME_PATH,
    process.env.GOOGLE_CHROME_BIN,
    '/usr/bin/google-chrome',
    '/usr/bin/google-chrome-stable',
    '/usr/bin/chromium-browser',
    '/usr/bin/chromium',
    '/snap/bin/chromium',
    ...macCandidates,
    ...windowsCandidates,
    ...pathCandidates
  ].filter((value): value is string => Boolean(value)))];
}

function shouldDisableSandbox(): boolean {
  const value = process.env.PUPPETEER_DISABLE_SANDBOX?.trim().toLowerCase();
  return value === '1' || value === 'true' || value === 'yes';
}

function extractStructuredValue(source: string, marker: string): string | null {
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) {
    return null;
  }

  let startIndex = markerIndex + marker.length;
  while (startIndex < source.length && /\s/.test(source[startIndex])) {
    startIndex += 1;
  }

  const openingChar = source[startIndex];
  const closingChar = openingChar === '[' ? ']' : openingChar === '{' ? '}' : null;
  if (!closingChar) {
    return null;
  }

  let depth = 0;
  let inString = false;
  let isEscaped = false;

  for (let index = startIndex; index < source.length; index++) {
    const char = source[index];

    if (inString) {
      if (isEscaped) {
        isEscaped = false;
      } else if (char === '\\') {
        isEscaped = true;
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === openingChar) {
      depth += 1;
    } else if (char === closingChar) {
      depth -= 1;
      if (depth === 0) {
        return source.slice(startIndex, index + 1);
      }
    }
  }

  return null;
}

function resolveChromeExecutablePath(): string {
  const executablePath = getChromeCandidates().find((candidate) => existsSync(candidate));
  if (!executablePath) {
    throw new Error('Could not find a Chrome or Chromium executable. Set CHROME_PATH or PUPPETEER_EXECUTABLE_PATH.');
  }
  return executablePath;
}

async function getBrowser(): Promise<Browser> {
  if (!browserPromise) {
    browserPromise = puppeteer.launch({
      executablePath: resolveChromeExecutablePath(),
      headless: true,
      args: shouldDisableSandbox() ? ['--no-sandbox', '--disable-setuid-sandbox'] : []
    }).catch((error) => {
      browserPromise = null;
      throw error;
    });
  }
  return browserPromise;
}

async function closeBrowser(): Promise<void> {
  if (!browserPromise) {
    return;
  }

  const currentBrowserPromise = browserPromise;
  browserPromise = null;
  const browser = await currentBrowserPromise;
  await browser.close();
}

export async function shutdownFetcher(): Promise<void> {
  await closeBrowser();
}

function httpsRequest(options: https.RequestOptions): Promise<string> {
  return new Promise((resolve, reject) => {
    const req = https.request({ ...options, timeout: REQUEST_TIMEOUT }, (res) => {
      if (res.statusCode && (res.statusCode < 200 || res.statusCode >= 300)) {
        reject(new Error(`HTTP ${res.statusCode}: ${res.statusMessage || 'Unknown error'}`));
        return;
      }

      let body = '';
      res.on('data', (chunk) => {
        body += chunk;
      });
      res.on('end', () => resolve(body));
    });

    req.on('error', (err) => {
      reject(new Error(`Network error: ${err.message}`));
    });

    req.on('timeout', () => {
      req.destroy();
      reject(new Error(`Request timeout after ${REQUEST_TIMEOUT}ms`));
    });

    req.end();
  });
}

function parseCaptionTracks(html: string): CaptionTrack[] {
  const serializedTracks = extractStructuredValue(html, '"captionTracks":');
  if (!serializedTracks) {
    return [];
  }

  try {
    const tracks = JSON.parse(serializedTracks);
    return uniqueLanguageCodes(
      tracks
        .filter((track: any) => Boolean(track?.languageCode))
        .map((track: any) => ({
          languageCode: String(track.languageCode),
          name: track.name?.simpleText || track.name?.runs?.[0]?.text || String(track.languageCode),
          isAutoGenerated: track.kind === 'asr'
        }))
    );
  } catch {
    console.error('[youtube-fetcher] Warning: Could not parse caption tracks');
    return [];
  }
}

async function getPageData(videoId: string): Promise<PageData> {
  let html: string;

  try {
    html = await httpsRequest({
      hostname: 'www.youtube.com',
      path: `/watch?v=${videoId}`,
      method: 'GET',
      headers: {
        'User-Agent': WATCH_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });
  } catch (err) {
    throw new Error(`Failed to fetch video page: ${(err as Error).message}`);
  }

  const availableLanguages = parseCaptionTracks(html);

  const adChapters: AdChapter[] = [];
  const adMarkers = [
    '(werbung)', '(ad)', '(ads)', '(sponsor)', '(sponsored)',
    '(promo)', '(promotion)', '(anzeige)', '(reklame)',
    '[werbung]', '[ad]', '[ads]', '[sponsor]', '[sponsored]',
    '[promo]', '[promotion]', '[anzeige]', '[reklame]'
  ];

  const chapterMatches = [...html.matchAll(/"chapterRenderer":\s*\{[^}]*"title":\s*\{\s*"simpleText":\s*"([^"]+)"[^}]*\}[^}]*"timeRangeStartMillis":\s*"?(\d+)"?/g)];

  interface Chapter {
    title: string;
    startMs: number;
    isAd: boolean;
  }

  const chapters: Chapter[] = chapterMatches.map((match) => ({
    title: match[1],
    startMs: parseInt(match[2], 10),
    isAd: adMarkers.some((marker) => match[1].toLowerCase().includes(marker))
  }));

  for (let index = 0; index < chapters.length; index++) {
    if (!chapters[index].isAd) {
      continue;
    }
    const nextChapter = chapters[index + 1];
    adChapters.push({
      title: chapters[index].title,
      startMs: chapters[index].startMs,
      endMs: nextChapter ? nextChapter.startMs : chapters[index].startMs + 300000
    });
  }

  const titleMatch = html.match(/"videoDetails":\{.*?"title":"([^"]+)"/);
  const authorMatch = html.match(/"videoDetails":\{.*?"author":"([^"]+)"/);
  const subsMatch = html.match(/"subscriberCountText":\{"accessibility":\{"accessibilityData":\{"label":"([^"]+)"/);
  const viewsMatch = html.match(/"viewCount":"(\d+)"/);
  const dateMatch = html.match(/"publishDate":"([^"]+)"/);

  let subscriberCount = subsMatch?.[1] || '';
  subscriberCount = subscriberCount
    .replace(/ subscribers?/i, '')
    .replace(/ thousand/i, 'k')
    .replace(/ million/i, 'M')
    .replace(/ billion/i, 'B');

  const rawViews = viewsMatch?.[1] || '';
  const viewNum = parseInt(rawViews, 10);
  const viewCount = Number.isNaN(viewNum)
    ? ''
    : viewNum >= 1_000_000
      ? `${(viewNum / 1_000_000).toFixed(1)}M`
      : viewNum >= 1_000
        ? `${(viewNum / 1_000).toFixed(1)}k`
        : rawViews;

  return {
    availableLanguages,
    adChapters,
    metadata: {
      title: titleMatch?.[1] || '',
      author: authorMatch?.[1] || '',
      subscriberCount,
      viewCount,
      publishDate: (dateMatch?.[1] || '').split('T')[0]
    }
  };
}

function normalizeLanguageCode(languageCode: string): string {
  return languageCode.trim().toLowerCase();
}

function selectLanguage(availableLanguages: CaptionTrack[], requestedLanguage: string, enableFallback: boolean): string {
  if (availableLanguages.length === 0) {
    return requestedLanguage;
  }

  const normalizedRequested = normalizeLanguageCode(requestedLanguage);
  const exactMatch = availableLanguages.find((track) => normalizeLanguageCode(track.languageCode) === normalizedRequested);
  if (exactMatch) {
    return exactMatch.languageCode;
  }

  const prefixMatch = availableLanguages.find((track) => normalizeLanguageCode(track.languageCode).startsWith(`${normalizedRequested}-`));
  if (prefixMatch) {
    return prefixMatch.languageCode;
  }

  if (!enableFallback) {
    throw new Error(`Language '${requestedLanguage}' not available. Available: ${availableLanguages.map((track) => track.languageCode).join(', ')}`);
  }

  const englishMatch = availableLanguages.find((track) => normalizeLanguageCode(track.languageCode) === 'en');
  if (englishMatch) {
    console.error(`[youtube-fetcher] Language '${requestedLanguage}' not available, falling back to '${englishMatch.languageCode}'`);
    return englishMatch.languageCode;
  }

  console.error(`[youtube-fetcher] Language '${requestedLanguage}' not available, falling back to '${availableLanguages[0].languageCode}'`);
  return availableLanguages[0].languageCode;
}

function parseTimestampToSeconds(timestamp: string): number {
  const parts = timestamp
    .split(':')
    .map((part) => parseInt(part, 10))
    .filter((value) => !Number.isNaN(value));

  if (parts.length === 0) {
    return 0;
  }

  return parts.reduce((total, part) => total * 60 + part, 0);
}

async function scrollTranscriptPanel(page: import('puppeteer-core').Page): Promise<void> {
  let previousCount = -1;
  let stableReads = 0;

  for (let attempt = 0; attempt < 20 && stableReads < 2; attempt++) {
    const count = await page.$$eval(
      'ytd-engagement-panel-section-list-renderer[target-id="PAmodern_transcript_view"] .ytwTranscriptSegmentViewModelHost',
      (elements) => elements.length
    );

    if (count === previousCount) {
      stableReads += 1;
    } else {
      previousCount = count;
      stableReads = 0;
    }

    await page.evaluate(() => {
      const panel = document.querySelector('ytd-engagement-panel-section-list-renderer[target-id="PAmodern_transcript_view"]');
      if (!panel) {
        return;
      }

      const scrollers = [panel, ...Array.from(panel.querySelectorAll('*'))].filter((element) => {
        const htmlElement = element as HTMLElement;
        return htmlElement.scrollHeight > htmlElement.clientHeight + 16;
      }) as HTMLElement[];

      const scroller = scrollers.sort((left, right) => right.scrollHeight - left.scrollHeight)[0];
      if (scroller) {
        scroller.scrollTop = scroller.scrollHeight;
      }
    });

    await new Promise((resolve) => setTimeout(resolve, 250));
  }
}

async function fetchTranscriptSegments(videoId: string, languageCode: string): Promise<TranscriptSegment[]> {
  const browser = await getBrowser();
  const page = await browser.newPage();

  try {
    await page.setViewport({ width: 1400, height: 2200 });
    await page.setUserAgent(WATCH_USER_AGENT);
    await page.setExtraHTTPHeaders({
      'Accept-Language': `${languageCode},en;q=0.8`
    });

    const watchUrl = `https://www.youtube.com/watch?v=${videoId}&hl=${encodeURIComponent(languageCode)}&persist_hl=1`;
    await page.goto(watchUrl, { waitUntil: 'networkidle2', timeout: REQUEST_TIMEOUT });

    await page.waitForSelector('ytd-video-description-transcript-section-renderer button', { timeout: 10000 });
    await page.evaluate(() => {
      const button = document.querySelector('ytd-video-description-transcript-section-renderer button') as HTMLElement | null;
      button?.click();
    });

    await page.waitForSelector('ytd-engagement-panel-section-list-renderer[target-id="PAmodern_transcript_view"]', { timeout: 10000 });
    await page.waitForFunction(
      () => document.querySelectorAll('ytd-engagement-panel-section-list-renderer[target-id="PAmodern_transcript_view"] .ytwTranscriptSegmentViewModelHost').length > 0,
      { timeout: 10000 }
    );

    await scrollTranscriptPanel(page);

    return await page.$$eval(
      'ytd-engagement-panel-section-list-renderer[target-id="PAmodern_transcript_view"] .ytwTranscriptSegmentViewModelHost',
      (elements) => {
        const segments = elements.map((element) => {
          const timestamp = element.querySelector('.ytwTranscriptSegmentViewModelTimestamp')?.textContent?.trim() || '';
          const text = Array.from(element.querySelectorAll('.yt-core-attributed-string'))
            .map((node) => node.textContent?.trim() || '')
            .filter(Boolean)
            .join(' ')
            .replace(/\s+/g, ' ')
            .trim();

          return { timestamp, text };
        });

        const seen = new Set<string>();
        return segments.filter((segment) => {
          if (!segment.timestamp || !segment.text) {
            return false;
          }
          const key = `${segment.timestamp}\n${segment.text}`;
          if (seen.has(key)) {
            return false;
          }
          seen.add(key);
          return true;
        });
      }
    );
  } finally {
    await page.close();
  }
}

function toTranscriptLines(segments: TranscriptSegment[]): TranscriptLine[] {
  return segments.map((segment, index) => {
    const start = parseTimestampToSeconds(segment.timestamp);
    const nextStart = index < segments.length - 1 ? parseTimestampToSeconds(segments[index + 1].timestamp) : start;
    return {
      text: segment.text,
      start,
      dur: Math.max(nextStart - start, 0)
    };
  });
}

export interface SubtitleResult {
  lines: TranscriptLine[];
  requestedLang: string;
  actualLang: string;
  availableLanguages: CaptionTrack[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
}

export async function getAvailableLanguages(videoID: string): Promise<CaptionTrack[]> {
  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }
  const { availableLanguages } = await getPageData(videoID);
  return availableLanguages;
}

export async function getSubtitles(options: {
  videoID: string;
  lang?: string;
  enableFallback?: boolean;
}): Promise<SubtitleResult> {
  const { videoID, lang = 'en', enableFallback = true } = options;

  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }

  const { availableLanguages, adChapters, metadata } = await getPageData(videoID);
  const actualLang = selectLanguage(availableLanguages, lang, enableFallback);
  const segments = await fetchTranscriptSegments(videoID, actualLang);

  if (segments.length === 0) {
    throw new Error('No transcript available for this video. The video may not have captions enabled.');
  }

  return {
    lines: toTranscriptLines(segments),
    requestedLang: lang,
    actualLang,
    availableLanguages,
    adChapters,
    metadata
  };
}
