import https from 'https';

/**
 * Error thrown when transcript fetch fails but page data was retrieved.
 * Carries isLive and metadata so callers can redirect to live chat.
 */
export class TranscriptFetchError extends Error {
  isLive: boolean;
  metadata: VideoMetadata;
  constructor(message: string, isLive: boolean, metadata: VideoMetadata) {
    super(message);
    this.name = 'TranscriptFetchError';
    this.isLive = isLive;
    this.metadata = metadata;
  }
}

export interface TranscriptLine {
  text: string;
  start: number;
  dur: number;
}

interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface AdChapter {
  title: string;
  startMs: number;
  endMs: number;
}

export interface VideoMetadata {
  title: string;
  author: string;
  subscriberCount: string;
  viewCount: string;
  commentCount: string;
  publishDate: string;
  duration: string;
}

export interface Chapter {
  title: string;
  startMs: number;
  isAd: boolean;
}

export interface Comment {
  author: string;
  authorChannelId: string;
  text: string;
  likes: string;
  replyCount: number;
  publishedTime: string;
  isPinned: boolean;
  isHearted: boolean;
  commentId: string;
  isReply: boolean;
  parentId?: string;
}

interface PageData {
  visitorData: string;
  clientVersion: string;
  apiKey: string;
  availableLanguages: CaptionTrack[];
  chapters: Chapter[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
  isLive: boolean;
  commentCount?: number;  // Optional - requires separate API call
}

const REQUEST_TIMEOUT = 30000; // 30 seconds
const RETRY_DELAYS = [1000, 2000]; // Retry after 1s, then 2s
const RETRYABLE_CODES = new Set([400, 408, 429, 500, 502, 503, 504]);

/**
 * Formats a number as compact string: 1234 → "1.2k", 1234567 → "1.2M"
 */
export function formatCount(n: number): string {
  if (Number.isNaN(n) || n <= 0) return '';
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M';
  if (n >= 1_000) return (n / 1_000).toFixed(1) + 'k';
  return n.toString();
}

// TODO: These versions may need periodic updates if YouTube starts rejecting old clients
// The ANDROID client is used against /youtubei/v1/player because the caption track URLs
// it returns are served without poToken enforcement (WEB player responses are not)
const ANDROID_CLIENT_VERSION = '20.10.38';
const ANDROID_USER_AGENT = `com.google.android.youtube/${ANDROID_CLIENT_VERSION} (Linux; U; Android 11) gzip`;
const WEB_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const DEFAULT_CLIENT_VERSION = '2.20260301.00.00'; // Fallback if not extracted from page

/**
 * Encodes a number as a protobuf varint
 * Handles lengths > 127 correctly (multi-byte encoding)
 */
function encodeVarint(value: number): number[] {
  const bytes: number[] = [];
  while (value > 0x7f) {
    bytes.push((value & 0x7f) | 0x80);
    value >>>= 7;
  }
  bytes.push(value);
  return bytes;
}

interface PlayerCaptionTrack extends CaptionTrack {
  baseUrl: string;
}

/**
 * Fetches caption track metadata (including download URLs) from the InnerTube player API.
 * Uses the ANDROID client: its caption baseUrls are not gated behind poToken.
 */
async function getPlayerCaptionTracks(videoId: string, apiKey: string): Promise<PlayerCaptionTrack[]> {
  const payload = JSON.stringify({
    context: {
      client: {
        hl: 'en',
        gl: 'US',
        clientName: 'ANDROID',
        clientVersion: ANDROID_CLIENT_VERSION,
        androidSdkVersion: 30
      }
    },
    videoId: videoId
  });

  const path = apiKey
    ? `/youtubei/v1/player?key=${apiKey}&prettyPrint=false`
    : '/youtubei/v1/player?prettyPrint=false';

  const response = await httpsRequest({
    hostname: 'www.youtube.com',
    path,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(payload),
      'User-Agent': ANDROID_USER_AGENT
    }
  }, payload);

  let json: any;
  try {
    json = JSON.parse(response);
  } catch (err) {
    throw new Error(`Failed to parse player API response: ${(err as Error).message}`);
  }
  if (json.error) {
    throw new Error(`YouTube player API error: ${json.error.message || json.error.code}`);
  }

  const status = json?.playabilityStatus?.status;
  if (status && status !== 'OK') {
    const reason = json?.playabilityStatus?.reason || status;
    console.error(`[youtube-fetcher] Player API playability: ${status} (${reason})`);
  }

  const tracks = json?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
  return tracks
    .filter((t: any) => t.baseUrl && t.languageCode)
    .map((t: any) => ({
      languageCode: t.languageCode,
      name: t.name?.simpleText || t.name?.runs?.[0]?.text || t.languageCode,
      isAutoGenerated: t.kind === 'asr',
      baseUrl: t.baseUrl
    }));
}

function decodeXmlEntities(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(parseInt(code, 10)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');
}

/**
 * Parses timedtext XML (<text start="1.36" dur="2.8">...</text>) into transcript lines.
 */
function parseTimedTextXml(xml: string): TranscriptLine[] {
  const lines: TranscriptLine[] = [];
  const textRegex = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  let match: RegExpExecArray | null;
  while ((match = textRegex.exec(xml)) !== null) {
    const attrs = match[1];
    const start = parseFloat(attrs.match(/start="([\d.]+)"/)?.[1] || '0');
    const dur = parseFloat(attrs.match(/dur="([\d.]+)"/)?.[1] || '0');
    // Strip inline markup before decoding so entity-encoded '<' in speech survives;
    // decode twice because timedtext double-encodes (apostrophe arrives as &amp;#39;)
    const text = decodeXmlEntities(decodeXmlEntities(match[2].replace(/<[^>]+>/g, '')))
      .replace(/\s+/g, ' ')
      .trim();
    if (text.length > 0) {
      lines.push({ text, start, dur });
    }
  }
  return lines;
}

/**
 * Builds the protobuf-encoded params for the comments API
 * Structure: GetCommentsSectionParams from YouTube.js proto definitions
 */
function buildCommentsParams(videoId: string, sortBy: 0 | 1 = 0): string {
  // Helper to encode a string field
  const encodeString = (fieldNum: number, str: string): number[] => {
    const tag = (fieldNum << 3) | 2; // wire type 2 = length-delimited
    return [tag, ...encodeVarint(str.length), ...Buffer.from(str)];
  };

  // Helper to encode a varint field
  const encodeVarField = (fieldNum: number, value: number): number[] => {
    const tag = (fieldNum << 3) | 0; // wire type 0 = varint
    return [tag, ...encodeVarint(value)];
  };

  // Helper to encode a submessage
  const encodeSubmessage = (fieldNum: number, content: number[]): number[] => {
    const tag = (fieldNum << 3) | 2;
    return [tag, ...encodeVarint(content.length), ...content];
  };

  // Build Options (field 4 of Params)
  // video_id=4, sort_by=6, type=15
  const options: number[] = [
    ...encodeString(4, videoId),
    ...encodeVarField(6, sortBy),
    ...encodeVarField(15, 2)  // type = 2
  ];

  // Build Params (field 6)
  // opts=4, target=8
  const params: number[] = [
    ...encodeSubmessage(4, options),
    ...encodeString(8, 'comments-section')
  ];

  // Build Context (field 2)
  const ctx: number[] = [
    ...encodeString(2, videoId)
  ];

  // Build full GetCommentsSectionParams
  // ctx=2, unk_param=3, params=6
  const full: number[] = [
    ...encodeSubmessage(2, ctx),
    ...encodeVarField(3, 6),  // unk_param = 6
    ...encodeSubmessage(6, params)
  ];

  return Buffer.from(full).toString('base64');
}

/**
 * Makes a single HTTPS request and returns the response body
 */
function httpsRequestOnce(options: https.RequestOptions, data?: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const req = https.request({ ...options, timeout: REQUEST_TIMEOUT }, (res) => {
      if (res.statusCode && (res.statusCode < 200 || res.statusCode >= 300)) {
        reject(new Error(`HTTP ${res.statusCode}: ${res.statusMessage || 'Unknown error'}`));
        return;
      }

      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => resolve(body));
    });

    req.on('error', (err) => {
      reject(new Error(`Network error: ${err.message}`));
    });

    req.on('timeout', () => {
      req.destroy();
      reject(new Error(`Request timeout after ${REQUEST_TIMEOUT}ms`));
    });

    if (data) req.write(data);
    req.end();
  });
}

/**
 * HTTPS request with automatic retry for transient errors (400, 408, 429, 5xx)
 */
async function httpsRequest(options: https.RequestOptions, data?: string): Promise<string> {
  for (let attempt = 0; attempt <= RETRY_DELAYS.length; attempt++) {
    try {
      return await httpsRequestOnce(options, data);
    } catch (err) {
      const message = (err as Error).message;
      const statusMatch = message.match(/^HTTP (\d+):/);
      const isRetryable = statusMatch && RETRYABLE_CODES.has(Number(statusMatch[1]));

      if (isRetryable && attempt < RETRY_DELAYS.length) {
        console.error(`[httpsRequest] ${options.path} — ${message}, retrying in ${RETRY_DELAYS[attempt]}ms (attempt ${attempt + 1}/${RETRY_DELAYS.length})`);
        await new Promise(r => setTimeout(r, RETRY_DELAYS[attempt]));
        continue;
      }
      throw err;
    }
  }
  throw new Error('httpsRequest: exhausted retries');
}

/**
 * Fetches the YouTube video page and extracts visitor data and client version
 */
async function getPageData(videoId: string): Promise<PageData> {
  let html: string;

  try {
    html = await httpsRequest({
      hostname: 'www.youtube.com',
      path: `/watch?v=${videoId}`,
      method: 'GET',
      headers: {
        'User-Agent': WEB_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });
  } catch (err) {
    throw new Error(`Failed to fetch video page: ${(err as Error).message}`);
  }

  // Check for video availability issues
  if (html.includes('"status":"LOGIN_REQUIRED"') ||
      html.includes('"reason":"Sign in to confirm your age') ||
      html.includes('ageGate') ||
      html.includes('"AGE_VERIFICATION_REQUIRED"')) {
    throw new Error('This video is age-restricted and requires sign-in to view. Transcripts cannot be retrieved for age-restricted content.');
  }

  if (html.includes('"status":"UNPLAYABLE"') || html.includes('"status":"ERROR"')) {
    // Extract reason if available
    const reasonMatch = html.match(/"reason":"([^"]+)"/);
    const reason = reasonMatch?.[1] || 'Video is unavailable';
    throw new Error(`Video unavailable: ${reason}`);
  }

  if (html.includes('"isPrivate":true')) {
    throw new Error('This video is private and cannot be accessed.');
  }

  if (html.includes('"status":"LIVE_STREAM_OFFLINE"')) {
    throw new Error('This is a live stream that is currently offline. No transcript available.');
  }

  // Extract visitor data
  const visitorMatch = html.match(/"visitorData":"([^"]+)"/);
  const visitorData = visitorMatch?.[1] || '';

  if (!visitorData) {
    console.error(`[youtube-fetcher] Warning: Could not extract visitorData for video ${videoId}. Request may fail.`);
  }

  // Extract client version (format: "2.YYYYMMDD.XX.XX")
  const versionMatch = html.match(/"clientVersion":"([\d.]+)"/);
  const clientVersion = versionMatch?.[1] || DEFAULT_CLIENT_VERSION;

  // Extract InnerTube API key (used for player API calls)
  const apiKeyMatch = html.match(/"INNERTUBE_API_KEY":\s*"([a-zA-Z0-9_-]+)"/);
  const apiKey = apiKeyMatch?.[1] || '';

  // Extract available caption tracks
  const availableLanguages: CaptionTrack[] = [];
  const captionsMatch = html.match(/"captions":\{"playerCaptionsTracklistRenderer":\{"captionTracks":(\[[^\]]+\])/);
  if (captionsMatch) {
    try {
      const tracks = JSON.parse(captionsMatch[1]);
      for (const track of tracks) {
        if (track.languageCode) {
          availableLanguages.push({
            languageCode: track.languageCode,
            name: track.name?.simpleText || track.name?.runs?.[0]?.text || track.languageCode,
            isAutoGenerated: track.kind === 'asr'
          });
        }
      }
    } catch (e) {
      console.error(`[youtube-fetcher] Warning: Could not parse caption tracks for video ${videoId}`);
    }
  }

  // Extract chapters and identify ad chapters
  const adChapters: AdChapter[] = [];
  const adMarkers = [
    '(werbung)', '(ad)', '(ads)', '(sponsor)', '(sponsored)',
    '(promo)', '(promotion)', '(anzeige)', '(reklame)',
    '[werbung]', '[ad]', '[ads]', '[sponsor]', '[sponsored]',
    '[promo]', '[promotion]', '[anzeige]', '[reklame]'
  ];

  // Extract chapters from chapterRenderer elements using individual field matches
  // Each chapterRenderer has a title and timeRangeStartMillis - extract all instances
  const chapters: Chapter[] = [];
  let searchPos = 0;
  while (true) {
    const chapterIdx = html.indexOf('"chapterRenderer"', searchPos);
    if (chapterIdx === -1) break;

    // Find the next chapterRenderer boundary (or end of string) for scoping
    const nextChapterIdx = html.indexOf('"chapterRenderer"', chapterIdx + 1);
    const chapterBlock = html.slice(chapterIdx, nextChapterIdx !== -1 ? nextChapterIdx : chapterIdx + 2000);

    // Extract title - try simpleText first, then runs[0].text
    const titleSimple = chapterBlock.match(/"title":\s*\{\s*"simpleText":\s*"([^"]+)"/);
    const titleRuns = chapterBlock.match(/"title":\s*\{\s*"runs":\s*\[\s*\{\s*"text":\s*"([^"]+)"/);
    const title = titleSimple?.[1] || titleRuns?.[1] || '';

    // Extract time
    const timeMatch = chapterBlock.match(/"timeRangeStartMillis":\s*"?(\d+)"?/);
    const startMs = timeMatch ? parseInt(timeMatch[1], 10) : -1;

    if (title && startMs >= 0) {
      chapters.push({
        title,
        startMs,
        isAd: adMarkers.some(marker => title.toLowerCase().includes(marker))
      });
    }

    searchPos = chapterIdx + 1;
  }

  // Convert ad chapters to AdChapter format with end times
  for (let i = 0; i < chapters.length; i++) {
    if (chapters[i].isAd) {
      const nextChapter = chapters[i + 1];
      // End time is start of next chapter, or +5 minutes if last chapter
      const endMs = nextChapter ? nextChapter.startMs : chapters[i].startMs + 300000;
      adChapters.push({
        title: chapters[i].title,
        startMs: chapters[i].startMs,
        endMs: endMs
      });
    }
  }

  // Extract video metadata (target videoDetails block, use .*? for nested objects)
  const titleMatch = html.match(/"videoDetails":\{.*?"title":"([^"]+)"/);
  const authorMatch = html.match(/"videoDetails":\{.*?"author":"([^"]+)"/);
  const subsMatch = html.match(/"subscriberCountText":\{"accessibility":\{"accessibilityData":\{"label":"([^"]+)"/);
  const viewsMatch = html.match(/"viewCount":"(\d+)"/);
  const dateMatch = html.match(/"publishDate":"([^"]+)"/);
  const lengthMatch = html.match(/"videoDetails":\{.*?"lengthSeconds":"(\d+)"/);
  
  // Extract comment count (may be in different locations in the HTML)
  const commentCountMatch = html.match(/"commentCount":"?(\d+)"?/) || 
                            html.match(/"commentCountText":\{"runs":\[\{"text":"([\d,]+)"/);

  // Shorten subscriber count: "649 thousand subscribers" → "649k"
  let subs = subsMatch?.[1] || '';
  subs = subs.replace(/ subscribers?/i, '').replace(/ thousand/i, 'k').replace(/ million/i, 'M').replace(/ billion/i, 'B');

  // Format view count and comment count
  const viewNum = parseInt(viewsMatch?.[1] || '', 10);
  const viewsFormatted = formatCount(viewNum);

  const commentNum = parseInt((commentCountMatch?.[1] || '').replace(/,/g, ''), 10);
  const commentsFormatted = formatCount(commentNum);

  // Shorten date: "2025-12-03T03:01:16-08:00" → "2025-12-03"
  const dateRaw = dateMatch?.[1] || '';
  const dateShort = dateRaw.split('T')[0];

  // Format duration: 212 → "3:32", 3661 → "1:01:01"
  const lengthSecs = parseInt(lengthMatch?.[1] || '0', 10);
  let durationFormatted = '';
  if (lengthSecs > 0) {
    const hrs = Math.floor(lengthSecs / 3600);
    const mins = Math.floor((lengthSecs % 3600) / 60);
    const secs = lengthSecs % 60;
    durationFormatted = hrs > 0
      ? `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`
      : `${mins}:${secs.toString().padStart(2, '0')}`;
  }

  const metadata: VideoMetadata = {
    title: titleMatch?.[1] || '',
    author: authorMatch?.[1] || '',
    subscriberCount: subs,
    viewCount: viewsFormatted,
    commentCount: commentsFormatted,
    publishDate: dateShort,
    duration: durationFormatted
  };

  // Detect live streams
  const isLive = html.includes('"isLiveContent":true') || html.includes('"isLive":true');

  return { visitorData, clientVersion, apiKey, availableLanguages, chapters, adChapters, metadata, isLive };
}

export interface SubtitleResult {
  lines: TranscriptLine[];
  requestedLang: string;
  actualLang: string;
  availableLanguages: CaptionTrack[];
  chapters: Chapter[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
  isLive: boolean;
}

/**
 * Returns available caption languages for a video without fetching the full transcript
 */
export async function getAvailableLanguages(videoID: string): Promise<CaptionTrack[]> {
  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }
  const { availableLanguages } = await getPageData(videoID);
  return availableLanguages;
}

/**
 * Fetches transcript using the YouTube internal API
 * If the requested language is not available and enableFallback is true,
 * it will try English first, then fall back to the first available language.
 */
export async function getSubtitles(options: {
  videoID: string;
  lang?: string;
  enableFallback?: boolean;
}): Promise<SubtitleResult> {
  const { videoID, lang = 'en', enableFallback = true } = options;

  // Validate video ID format
  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }

  // Get page data (metadata, chapters, live status; caption list fallback)
  console.error(`[youtube-fetcher] Fetching page data for video: ${videoID}`);
  const { apiKey, availableLanguages: pageLanguages, chapters, adChapters, metadata, isLive } = await getPageData(videoID);
  console.error(`[youtube-fetcher] Page data: title="${metadata.title}", apiKey=${apiKey ? 'present' : 'MISSING'}`);

  // Fetch caption tracks (with download URLs) from the player API
  let playerTracks: PlayerCaptionTrack[];
  try {
    playerTracks = await getPlayerCaptionTracks(videoID, apiKey);
  } catch (err) {
    throw new TranscriptFetchError(`Failed to fetch caption tracks: ${(err as Error).message}`, isLive, metadata);
  }
  console.error(`[youtube-fetcher] Player API caption tracks: [${playerTracks.map(t => t.languageCode + (t.isAutoGenerated ? '(asr)' : '')).join(',')}]`);

  const availableLanguages: CaptionTrack[] = playerTracks.length > 0
    ? playerTracks.map(({ languageCode, name, isAutoGenerated }) => ({ languageCode, name, isAutoGenerated }))
    : pageLanguages;

  if (playerTracks.length === 0) {
    throw new TranscriptFetchError('No transcript available for this video. The video may not have captions enabled.', isLive, metadata);
  }

  // Select track: requested language, else English, else first available
  let track = playerTracks.find(t => t.languageCode === lang);
  if (!track) {
    if (!enableFallback) {
      throw new Error(`Language '${lang}' not available. Available: ${playerTracks.map(t => t.languageCode).join(', ')}`);
    }
    track = playerTracks.find(t => t.languageCode === 'en') || playerTracks[0];
    console.error(`[youtube-fetcher] Language '${lang}' not available, falling back to '${track.languageCode}' (isAsr=${track.isAutoGenerated})`);
  }
  const targetLang = track.languageCode;

  // Caption URLs carrying exp=xpe are gated behind a proof-of-origin token
  if (track.baseUrl.includes('&exp=xpe')) {
    throw new TranscriptFetchError('YouTube requires a proof-of-origin token (poToken) for caption downloads from this IP. Transcript cannot be retrieved.', isLive, metadata);
  }

  // Download and parse the timedtext XML
  const trackUrl = new URL(track.baseUrl.replace('&fmt=srv3', ''));
  console.error(`[youtube-fetcher] Fetching timedtext for lang=${targetLang} (isAsr=${track.isAutoGenerated})`);
  const xml = await httpsRequest({
    hostname: trackUrl.hostname,
    path: trackUrl.pathname + trackUrl.search,
    method: 'GET',
    headers: {
      'User-Agent': ANDROID_USER_AGENT,
      'Accept-Language': 'en-US'
    }
  });

  const lines = parseTimedTextXml(xml);
  console.error(`[youtube-fetcher] Parsed ${lines.length} transcript lines`);

  if (lines.length === 0) {
    throw new TranscriptFetchError('No transcript available for this video. The video may not have captions enabled.', isLive, metadata);
  }

  // commentCount is already extracted from the page HTML in getPageData
  // No need for a separate API call that re-fetches the entire page

  return {
    lines,
    requestedLang: lang,
    actualLang: targetLang,
    availableLanguages,
    chapters,
    adChapters,
    metadata,
    isLive
  };
}

export interface CommentsResult {
  comments: Comment[];
  totalCount: number;
  continuation?: string;
}

interface CommentPageResult {
  comments: Comment[];
  totalCount: number;
  continuation?: string;
  replyTokens: Map<string, string>; // commentId -> reply continuation token
}

/**
 * Fetches a single page of comments using a continuation token
 */
async function fetchCommentsPage(
  continuationToken: string,
  visitorData: string,
  clientVersion: string
): Promise<CommentPageResult> {
  const payload = JSON.stringify({
    context: {
      client: {
        hl: 'en',
        gl: 'US',
        clientName: 'WEB',
        clientVersion: clientVersion,
        visitorData: visitorData
      }
    },
    continuation: continuationToken
  });

  const response = await httpsRequest({
    hostname: 'www.youtube.com',
    path: '/youtubei/v1/next?prettyPrint=false',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(payload),
      'User-Agent': WEB_USER_AGENT,
      'Origin': 'https://www.youtube.com'
    }
  }, payload);

  let json: any;
  try {
    json = JSON.parse(response);
  } catch (parseErr) {
    console.error(`[fetchCommentsPage] Failed to parse response: ${(parseErr as Error).message}`);
    throw new Error(`Failed to parse YouTube response in fetchCommentsPage: ${(parseErr as Error).message}`);
  }
  if (json.error) {
    throw new Error(`YouTube API error: ${json.error.message || 'Unknown error'}`);
  }

  const comments: Comment[] = [];
  let totalCount = 0;
  let nextContinuation: string | undefined;
  const replyTokens = new Map<string, string>();

  const endpoints = json.onResponseReceivedEndpoints || [];

  // Get total count, continuation, and reply tokens from endpoints
  for (const endpoint of endpoints) {
    const items = endpoint.reloadContinuationItemsCommand?.continuationItems ||
                  endpoint.appendContinuationItemsAction?.continuationItems || [];
    for (const item of items) {
      if (item.commentsHeaderRenderer) {
        const countText = item.commentsHeaderRenderer.countText?.runs?.[0]?.text || '';
        const countMatch = countText.match(/[\d,]+/);
        if (countMatch) {
          totalCount = parseInt(countMatch[0].replace(/,/g, ''), 10);
        }
      }
      if (item.continuationItemRenderer) {
        nextContinuation = item.continuationItemRenderer.continuationEndpoint?.continuationCommand?.token;
      }
      // Extract reply continuation tokens from comment threads
      if (item.commentThreadRenderer) {
        const thread = item.commentThreadRenderer;
        const vm = thread.commentViewModel?.commentViewModel;
        const commentId = vm?.commentId;
        const replies = thread.replies?.commentRepliesRenderer;
        if (commentId && replies) {
          // Look for continuation token in replies
          const replyContents = replies.contents || [];
          for (const rc of replyContents) {
            const token = rc.continuationItemRenderer?.continuationEndpoint?.continuationCommand?.token;
            if (token) {
              replyTokens.set(commentId, token);
              break;
            }
          }
        }
      }
    }
  }

  // Extract comments from frameworkUpdates (new YouTube API structure)
  const mutations = json.frameworkUpdates?.entityBatchUpdate?.mutations || [];
  const pinnedCommentIds = new Set<string>();

  // First pass: identify pinned comments from commentViewModel
  for (const endpoint of endpoints) {
    const items = endpoint.reloadContinuationItemsCommand?.continuationItems ||
                  endpoint.appendContinuationItemsAction?.continuationItems || [];
    for (const item of items) {
      const vm = item.commentThreadRenderer?.commentViewModel?.commentViewModel;
      if (vm?.pinnedText && vm.commentId) {
        pinnedCommentIds.add(vm.commentId);
      }
    }
  }

  // Second pass: extract comment data
  for (const mut of mutations) {
    const mutPayload = mut.payload?.commentEntityPayload;
    if (!mutPayload) continue;

    const props = mutPayload.properties || {};
    const author = mutPayload.author || {};
    const toolbar = mutPayload.toolbar || {};
    const commentId = props.commentId || '';

    comments.push({
      author: author.displayName || '',
      authorChannelId: author.channelId || '',
      text: props.content?.content || '',
      likes: toolbar.likeCountNotliked || '0',
      replyCount: parseInt(toolbar.replyCount || '0', 10),
      publishedTime: props.publishedTime || '',
      isPinned: pinnedCommentIds.has(commentId),
      isHearted: !!(toolbar.heartActiveTooltip),
      commentId,
      isReply: false
    });
  }

  return { comments, totalCount, continuation: nextContinuation, replyTokens };
}

/**
 * Fetches replies for a comment using its reply continuation token
 */
async function fetchReplies(
  replyToken: string,
  parentId: string,
  visitorData: string,
  clientVersion: string,
  maxReplies: number = 50
): Promise<Comment[]> {
  const replies: Comment[] = [];
  let token: string | undefined = replyToken;
  let pagesFetched = 0;
  const maxPages = 5;

  while (token && replies.length < maxReplies && pagesFetched < maxPages) {
    const payload = JSON.stringify({
      context: {
        client: {
          hl: 'en',
          gl: 'US',
          clientName: 'WEB',
          clientVersion: clientVersion,
          visitorData: visitorData
        }
      },
      continuation: token
    });

    try {
      const response = await httpsRequest({
        hostname: 'www.youtube.com',
        path: '/youtubei/v1/next?prettyPrint=false',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(payload),
          'User-Agent': WEB_USER_AGENT,
          'Origin': 'https://www.youtube.com'
        }
      }, payload);

      const json = JSON.parse(response);
      pagesFetched++;

      // Extract reply comments from mutations
      const mutations = json.frameworkUpdates?.entityBatchUpdate?.mutations || [];
      for (const mut of mutations) {
        const mutPayload = mut.payload?.commentEntityPayload;
        if (!mutPayload) continue;

        const props = mutPayload.properties || {};
        const author = mutPayload.author || {};
        const toolbar = mutPayload.toolbar || {};

        replies.push({
          author: author.displayName || '',
          authorChannelId: author.channelId || '',
          text: props.content?.content || '',
          likes: toolbar.likeCountNotliked || '0',
          replyCount: 0,
          publishedTime: props.publishedTime || '',
          isPinned: false,
          isHearted: !!(toolbar.heartActiveTooltip),
          commentId: props.commentId || '',
          isReply: true,
          parentId
        });
      }

      // Get next continuation token for more replies
      token = undefined;
      const endpoints = json.onResponseReceivedEndpoints || [];
      for (const endpoint of endpoints) {
        const items = endpoint.appendContinuationItemsAction?.continuationItems || [];
        for (const item of items) {
          if (item.continuationItemRenderer) {
            token = item.continuationItemRenderer.continuationEndpoint?.continuationCommand?.token;
            break;
          }
        }
        if (token) break;
      }
    } catch (err) {
      console.error('[youtube-fetcher] Error fetching replies:', err);
      break;
    }
  }

  return replies.slice(0, maxReplies);
}

/**
 * Fetches comments for a video using YouTube's internal API with pagination support
 */
export async function getComments(options: {
  videoID: string;
  sortBy?: 'TOP_COMMENTS' | 'NEWEST_FIRST';
  limit?: number;
}): Promise<CommentsResult> {
  const { videoID, sortBy = 'TOP_COMMENTS', limit = 20 } = options;

  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }

  // Get page data for visitorData
  const { visitorData, clientVersion } = await getPageData(videoID);

  // Build initial comments params (0 = TOP_COMMENTS, 1 = NEWEST_FIRST)
  const sortByNum = sortBy === 'NEWEST_FIRST' ? 1 : 0;
  let continuationToken: string | undefined = buildCommentsParams(videoID, sortByNum);

  const allComments: Comment[] = [];
  const allReplyTokens = new Map<string, string>();
  let totalCount = 0;
  const noLimit = limit === 0; // 0 means fetch all

  try {
    // First pass: fetch all top-level comments and collect reply tokens
    while (continuationToken && (noLimit || allComments.length < limit)) {
      const pageResult = await fetchCommentsPage(continuationToken, visitorData, clientVersion);

      if (pageResult.totalCount > 0) {
        totalCount = pageResult.totalCount;
      }

      allComments.push(...pageResult.comments);
      continuationToken = pageResult.continuation;

      // Collect reply tokens
      for (const [commentId, token] of pageResult.replyTokens) {
        allReplyTokens.set(commentId, token);
      }

      // If we got no new comments, stop
      if (pageResult.comments.length === 0) break;
    }

    // Second pass: fetch replies for comments that have them (if we have room)
    if ((noLimit || allComments.length < limit) && allReplyTokens.size > 0) {
      const commentsWithReplies = allComments.filter(c => c.replyCount > 0 && allReplyTokens.has(c.commentId));

      // Collect all replies keyed by parent ID to avoid mutating allComments during iteration
      const repliesByParent = new Map<string, Comment[]>();
      let totalRepliesFetched = 0;

      for (const comment of commentsWithReplies) {
        if (!noLimit && (allComments.length + totalRepliesFetched) >= limit) break;

        const replyToken = allReplyTokens.get(comment.commentId);
        if (!replyToken) continue;

        const remainingSlots = noLimit ? comment.replyCount : Math.min(limit - allComments.length - totalRepliesFetched, comment.replyCount);
        if (remainingSlots <= 0) break;

        const replies = await fetchReplies(replyToken, comment.commentId, visitorData, clientVersion, remainingSlots);
        repliesByParent.set(comment.commentId, replies);
        totalRepliesFetched += replies.length;
      }

      // Merge replies after parent comments (iterate in reverse to keep indices stable)
      const parentIds = [...repliesByParent.keys()];
      for (let i = parentIds.length - 1; i >= 0; i--) {
        const parentId = parentIds[i];
        const replies = repliesByParent.get(parentId)!;
        const parentIndex = allComments.findIndex(c => c.commentId === parentId);
        if (parentIndex !== -1) {
          allComments.splice(parentIndex + 1, 0, ...replies);
        } else {
          allComments.push(...replies);
        }
      }
    }
  } catch (err) {
    console.error('[youtube-fetcher] Error fetching comments:', err);
  }

  return {
    comments: noLimit ? allComments : allComments.slice(0, limit),
    totalCount,
    continuation: continuationToken
  };
}

// ==================== LIVE CHAT SUPPORT ====================

export interface LiveChatMessage {
  id: string;
  author: string;
  authorChannelId: string;
  text: string;
  timestampUsec: string;
  isPaid: boolean;
  paidAmount?: string;
}

export interface LiveChatResult {
  messages: LiveChatMessage[];
  continuation?: string;
  isLive: boolean;
  pollIntervalMs: number;
  videoTitle?: string;
  channelName?: string;
}

/**
 * Extracts live chat continuation token from video page
 */
async function getLiveChatContinuation(videoId: string): Promise<{
  continuation: string;
  isLive: boolean;
  visitorData: string;
  title?: string;
  author?: string;
}> {
  let html: string;

  try {
    html = await httpsRequest({
      hostname: 'www.youtube.com',
      path: `/watch?v=${videoId}`,
      method: 'GET',
      headers: {
        'User-Agent': WEB_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });
  } catch (err) {
    throw new Error(`Failed to fetch video page: ${(err as Error).message}`);
  }

  // Check if live
  const isLive = html.includes('"isLiveContent":true') || html.includes('"isLive":true');

  if (!isLive) {
    throw new Error('This video is not a live stream. Use get_transcript for regular videos.');
  }

  // Extract visitor data
  const visitorMatch = html.match(/"visitorData":"([^"]+)"/);
  const visitorData = visitorMatch?.[1] || '';

  // Extract continuation token specifically from live chat context
  // Try liveChatContinuation first, then liveChatRenderer, then broad fallback
  const liveChatContMatch = html.match(/"liveChatContinuation".*?"continuation":"([^"]+)"/s);
  const liveChatRendererMatch = html.match(/"liveChatRenderer".*?"continuation":"([^"]+)"/s);
  const continuationMatch = liveChatContMatch || liveChatRendererMatch || html.match(/"continuation":"([^"]+)"/);
  if (!continuationMatch) {
    throw new Error('Could not find live chat continuation token. The stream may have ended.');
  }

  // Extract metadata from videoDetails context (scoped to avoid unrelated matches)
  const videoDetailsMatch = html.match(/"videoDetails"\s*:\s*\{[^}]*?"title":"([^"]+)"[^}]*?"author":"([^"]+)"/s);
  const title = videoDetailsMatch?.[1] || html.match(/"title":"([^"]+)"/)?.[1];
  const author = videoDetailsMatch?.[2] || html.match(/"author":"([^"]+)"/)?.[1];

  return {
    continuation: continuationMatch[1],
    isLive,
    visitorData,
    title,
    author
  };
}

/**
 * Fetches live chat messages from a live stream
 */
export async function getLiveChat(options: {
  videoID: string;
  continuation?: string;
  visitorData?: string;
}): Promise<LiveChatResult & { visitorData: string }> {
  const { videoID } = options;
  let { continuation } = options;
  let visitorData = options.visitorData || '';
  let videoTitle: string | undefined;
  let channelName: string | undefined;

  // If no continuation provided, get it from the page
  if (!continuation) {
    const pageData = await getLiveChatContinuation(videoID);
    continuation = pageData.continuation;
    visitorData = pageData.visitorData;
    videoTitle = pageData.title;
    channelName = pageData.author;
  }

  // Fetch live chat
  const payload = JSON.stringify({
    context: {
      client: {
        clientName: 'WEB',
        clientVersion: DEFAULT_CLIENT_VERSION,
        visitorData: visitorData
      }
    },
    continuation: continuation
  });

  let response: string;
  try {
    response = await httpsRequest({
      hostname: 'www.youtube.com',
      path: '/youtubei/v1/live_chat/get_live_chat?key=AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload),
        'User-Agent': WEB_USER_AGENT,
        'Origin': 'https://www.youtube.com'
      }
    }, payload);
  } catch (err) {
    throw new Error(`Failed to fetch live chat: ${(err as Error).message}`);
  }

  let json: any;
  try {
    json = JSON.parse(response);
  } catch (parseErr) {
    console.error(`[getLiveChat] Failed to parse response as JSON: ${(parseErr as Error).message}`);
    throw new Error(`Live chat response is not valid JSON: ${(parseErr as Error).message}`);
  }

  if (json.error) {
    throw new Error(`YouTube API error: ${json.error.message || 'Unknown error'}`);
  }

  const messages: LiveChatMessage[] = [];
  let nextContinuation: string | undefined;
  let pollIntervalMs = 5000; // Default 5 seconds

  // Extract continuation and poll interval
  const liveChatContinuation = json.continuationContents?.liveChatContinuation;
  if (liveChatContinuation) {
    const continuations = liveChatContinuation.continuations || [];
    for (const cont of continuations) {
      const invalidation = cont.invalidationContinuationData || cont.timedContinuationData;
      if (invalidation) {
        nextContinuation = invalidation.continuation;
        pollIntervalMs = invalidation.timeoutMs || 5000;
        break;
      }
    }

    // Extract messages from actions
    const actions = liveChatContinuation.actions || [];
    for (const action of actions) {
      if (action.addChatItemAction) {
        const item = action.addChatItemAction.item;

        // Regular text message
        if (item.liveChatTextMessageRenderer) {
          const r = item.liveChatTextMessageRenderer;
          const text = (r.message?.runs || []).map((run: any) => run.text || '').join('');

          messages.push({
            id: r.id || '',
            author: r.authorName?.simpleText || '',
            authorChannelId: r.authorExternalChannelId || '',
            text,
            timestampUsec: r.timestampUsec || '',
            isPaid: false
          });
        }

        // Paid message (Super Chat)
        if (item.liveChatPaidMessageRenderer) {
          const r = item.liveChatPaidMessageRenderer;
          const text = (r.message?.runs || []).map((run: any) => run.text || '').join('');

          messages.push({
            id: r.id || '',
            author: r.authorName?.simpleText || '',
            authorChannelId: r.authorExternalChannelId || '',
            text,
            timestampUsec: r.timestampUsec || '',
            isPaid: true,
            paidAmount: r.purchaseAmountText?.simpleText || ''
          });
        }
      }
    }
  }

  return {
    messages,
    continuation: nextContinuation,
    isLive: Boolean(nextContinuation),
    pollIntervalMs,
    videoTitle,
    channelName,
    visitorData
  };
}

// ==================== BACKGROUND STREAMING ====================

interface LiveStreamState {
  videoId: string;
  visitorData: string;
  continuation: string;
  pollIntervalMs: number;
  messageBuffer: LiveChatMessage[];
  seenIds: Set<string>;
  isPolling: boolean;
  pollTimer: NodeJS.Timeout | null;
  videoTitle?: string;
  channelName?: string;
  startedAt: number;
  lastPollAt: number;
  totalMessagesFetched: number;
}

// Global state for background streams
const activeStreams: Map<string, LiveStreamState> = new Map();

/**
 * Check if a video is a live stream without throwing
 */
export async function checkIfLive(videoId: string): Promise<{
  isLive: boolean;
  title?: string;
  author?: string;
}> {
  try {
    const html = await httpsRequest({
      hostname: 'www.youtube.com',
      path: `/watch?v=${videoId}`,
      method: 'GET',
      headers: {
        'User-Agent': WEB_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });

    const isLive = html.includes('"isLiveContent":true') || html.includes('"isLive":true');
    // Scope to videoDetails to avoid matching recommended video titles
    const videoDetailsMatch = html.match(/"videoDetails"\s*:\s*\{[^}]*?"title":"([^"]+)"[^}]*?"author":"([^"]+)"/s);
    const title = videoDetailsMatch?.[1] || html.match(/"title":"([^"]+)"/)?.[1];
    const author = videoDetailsMatch?.[2] || html.match(/"author":"([^"]+)"/)?.[1];

    return {
      isLive,
      title,
      author
    };
  } catch {
    return { isLive: false };
  }
}

/**
 * Start background polling for a live stream
 */
export async function startLiveChatStream(videoId: string): Promise<LiveChatResult & { streaming: boolean }> {
  // Check if already streaming
  if (activeStreams.has(videoId)) {
    const state = activeStreams.get(videoId)!;
    // Return buffered messages and clear buffer
    const messages = [...state.messageBuffer];
    state.messageBuffer = [];

    return {
      messages,
      continuation: state.continuation,
      isLive: state.isPolling,
      pollIntervalMs: state.pollIntervalMs,
      videoTitle: state.videoTitle,
      channelName: state.channelName,
      streaming: true
    };
  }

  // Start new stream
  const result = await getLiveChat({ videoID: videoId });

  const state: LiveStreamState = {
    videoId,
    visitorData: result.visitorData,
    continuation: result.continuation || '',
    pollIntervalMs: result.pollIntervalMs,
    messageBuffer: [],
    seenIds: new Set(result.messages.map(m => m.id)),
    isPolling: true,
    pollTimer: null,
    videoTitle: result.videoTitle,
    channelName: result.channelName,
    startedAt: Date.now(),
    lastPollAt: Date.now(),
    totalMessagesFetched: result.messages.length
  };

  activeStreams.set(videoId, state);

  // Start background polling
  const poll = async () => {
    if (!state.isPolling) return;

    try {
      const newResult = await getLiveChat({
        videoID: videoId,
        continuation: state.continuation,
        visitorData: state.visitorData
      });

      state.lastPollAt = Date.now();
      state.continuation = newResult.continuation || state.continuation;
      state.pollIntervalMs = newResult.pollIntervalMs;

      // Count new messages before adding to seenIds
      let newMsgCount = 0;

      // Add only new messages to buffer
      for (const msg of newResult.messages) {
        if (!state.seenIds.has(msg.id)) {
          state.seenIds.add(msg.id);
          state.messageBuffer.push(msg);
          state.totalMessagesFetched++;
          newMsgCount++;
        }
      }

      // Cap buffer at 500 messages
      if (state.messageBuffer.length > 500) {
        state.messageBuffer = state.messageBuffer.slice(-500);
      }

      // Cap seenIds at 2000
      if (state.seenIds.size > 2000) {
        const arr = Array.from(state.seenIds);
        state.seenIds = new Set(arr.slice(-1500));
      }

      // Log new messages to stderr
      if (newMsgCount > 0) {
        process.stderr.write(`\n[LIVE] ${state.videoTitle || videoId} | +${newMsgCount} msgs | buffer: ${state.messageBuffer.length} | total: ${state.totalMessagesFetched}\n`);
        const lastMsg = state.messageBuffer[state.messageBuffer.length - 1];
        if (lastMsg) {
          process.stderr.write(`  └─ ${lastMsg.author}: ${lastMsg.text.slice(0, 60)}${lastMsg.text.length > 60 ? '...' : ''}\n`);
        }
      }

    } catch (err) {
      console.error(`[live-chat] Poll error for ${videoId}:`, err);
      // Stream may have ended
      if ((err as Error).message?.includes('ended')) {
        state.isPolling = false;
        if (state.pollTimer) clearTimeout(state.pollTimer);
        activeStreams.delete(videoId);
        return;
      }
    }

    // Schedule next poll
    if (state.isPolling) {
      state.pollTimer = setTimeout(poll, state.pollIntervalMs);
    }
  };

  // Start first background poll after initial delay
  state.pollTimer = setTimeout(poll, state.pollIntervalMs);

  return {
    ...result,
    streaming: true
  };
}

/**
 * Get buffered messages from an active stream
 */
export function getLiveChatBuffer(videoId: string): {
  messages: LiveChatMessage[];
  isStreaming: boolean;
  stats: {
    totalFetched: number;
    bufferSize: number;
    streamDurationMs: number;
    lastPollMs: number;
  };
  videoTitle?: string;
  channelName?: string;
} | null {
  const state = activeStreams.get(videoId);
  if (!state) return null;

  // Get and clear buffer
  const messages = [...state.messageBuffer];
  state.messageBuffer = [];

  return {
    messages,
    isStreaming: state.isPolling,
    stats: {
      totalFetched: state.totalMessagesFetched,
      bufferSize: messages.length,
      streamDurationMs: Date.now() - state.startedAt,
      lastPollMs: Date.now() - state.lastPollAt
    },
    videoTitle: state.videoTitle,
    channelName: state.channelName
  };
}

/**
 * Stop background polling for a live stream
 */
export function stopLiveChatStream(videoId: string): {
  stopped: boolean;
  finalMessages: LiveChatMessage[];
  stats: {
    totalFetched: number;
    streamDurationMs: number;
  };
} | null {
  const state = activeStreams.get(videoId);
  if (!state) return null;

  state.isPolling = false;
  if (state.pollTimer) {
    clearTimeout(state.pollTimer);
  }

  const finalMessages = [...state.messageBuffer];
  const stats = {
    totalFetched: state.totalMessagesFetched,
    streamDurationMs: Date.now() - state.startedAt
  };

  activeStreams.delete(videoId);

  return {
    stopped: true,
    finalMessages,
    stats
  };
}

/**
 * Stop all active streams and release resources. Call on process exit.
 */
export function stopAllStreams(): void {
  for (const [, state] of activeStreams) {
    state.isPolling = false;
    if (state.pollTimer) clearTimeout(state.pollTimer);
  }
  activeStreams.clear();
}

/**
 * List all active streams
 */
export function listActiveStreams(): Array<{
  videoId: string;
  videoTitle?: string;
  channelName?: string;
  isPolling: boolean;
  bufferSize: number;
  totalFetched: number;
  streamDurationMs: number;
}> {
  return Array.from(activeStreams.values()).map(state => ({
    videoId: state.videoId,
    videoTitle: state.videoTitle,
    channelName: state.channelName,
    isPolling: state.isPolling,
    bufferSize: state.messageBuffer.length,
    totalFetched: state.totalMessagesFetched,
    streamDurationMs: Date.now() - state.startedAt
  }));
}

