import { describe, it, expect, beforeAll } from 'vitest';
import { getSubtitles, getAvailableLanguages } from './youtube-fetcher.js';
import type { SubtitleResult, CaptionTrack } from './youtube-fetcher.js';

// Well-known stable videos with guaranteed captions
const RICK_ROLL    = 'dQw4w9WgXcQ'; // EN, auto-generated + manual
const FIRST_VIDEO  = 'jNQXAC9IVRw'; // "Me at the zoo" - short, EN captions
const TED_TALK     = 'UF8uR6Z6KLc'; // Steve Jobs Stanford 2005 - multi-language

const TIMEOUT = 30_000;

// Cache network results across tests to avoid hammering YouTube on every assertion
let rickRoll: SubtitleResult;
let rickRollLangs: CaptionTrack[];
let firstVideo: SubtitleResult;

beforeAll(async () => {
  [rickRoll, rickRollLangs, firstVideo] = await Promise.all([
    getSubtitles({ videoID: RICK_ROLL }),
    getAvailableLanguages(RICK_ROLL),
    getSubtitles({ videoID: FIRST_VIDEO }),
  ]);
}, TIMEOUT);

// ─── getAvailableLanguages ────────────────────────────────────────────────────

describe('getAvailableLanguages', () => {
  it('returns an array of caption tracks for a public video', () => {
    expect(Array.isArray(rickRollLangs)).toBe(true);
    expect(rickRollLangs.length).toBeGreaterThan(0);
  });

  it('each track has languageCode, name, isAutoGenerated', () => {
    for (const track of rickRollLangs) {
      expect(typeof track.languageCode).toBe('string');
      expect(track.languageCode.length).toBeGreaterThan(0);
      expect(typeof track.name).toBe('string');
      expect(typeof track.isAutoGenerated).toBe('boolean');
    }
  });

  it('throws on empty video ID', async () => {
    await expect(getAvailableLanguages('')).rejects.toThrow();
  });

  it('throws on non-string video ID', async () => {
    // @ts-expect-error intentional bad input
    await expect(getAvailableLanguages(null)).rejects.toThrow();
  });
});

// ─── getSubtitles ─────────────────────────────────────────────────────────────

describe('getSubtitles - response shape', () => {
  it('returns all required top-level fields', () => {
    expect(rickRoll).toHaveProperty('lines');
    expect(rickRoll).toHaveProperty('requestedLang');
    expect(rickRoll).toHaveProperty('actualLang');
    expect(rickRoll).toHaveProperty('availableLanguages');
    expect(rickRoll).toHaveProperty('adChapters');
    expect(rickRoll).toHaveProperty('metadata');
  });

  it('lines array is non-empty with valid shape', () => {
    expect(rickRoll.lines.length).toBeGreaterThan(0);
    for (const line of rickRoll.lines.slice(0, 5)) {
      expect(typeof line.text).toBe('string');
      expect(line.text.length).toBeGreaterThan(0);
      expect(typeof line.start).toBe('number');
      expect(typeof line.dur).toBe('number');
      expect(line.start).toBeGreaterThanOrEqual(0);
      expect(line.dur).toBeGreaterThan(0);
    }
  });

  it('timestamps are monotonically non-decreasing', () => {
    for (let i = 1; i < rickRoll.lines.length; i++) {
      expect(rickRoll.lines[i].start).toBeGreaterThanOrEqual(rickRoll.lines[i - 1].start);
    }
  });

  it('metadata has title and author', () => {
    expect(typeof rickRoll.metadata.title).toBe('string');
    expect(rickRoll.metadata.title.length).toBeGreaterThan(0);
    expect(typeof rickRoll.metadata.author).toBe('string');
    expect(rickRoll.metadata.author.length).toBeGreaterThan(0);
  });

  it('requestedLang matches what was asked', () => {
    expect(rickRoll.requestedLang).toBe('en');
  });
});

// ─── language handling ────────────────────────────────────────────────────────

describe('getSubtitles - language handling', () => {
  it('falls back to english when requested lang is unavailable', async () => {
    const result = await getSubtitles({ videoID: RICK_ROLL, lang: 'xx', enableFallback: true });
    expect(result.actualLang).toBe('en');
    expect(result.requestedLang).toBe('xx');
  }, TIMEOUT);

  it('throws when lang unavailable and fallback disabled', async () => {
    await expect(
      getSubtitles({ videoID: RICK_ROLL, lang: 'xx', enableFallback: false })
    ).rejects.toThrow(/not available/i);
  }, TIMEOUT);

  it('works with a short video (first YouTube video)', () => {
    expect(firstVideo.lines.length).toBeGreaterThan(0);
  });
});

// ─── error handling ───────────────────────────────────────────────────────────

describe('getSubtitles - error handling', () => {
  it('throws on empty video ID', async () => {
    await expect(getSubtitles({ videoID: '' })).rejects.toThrow();
  });

  it('throws a descriptive error on a nonexistent video', async () => {
    await expect(
      getSubtitles({ videoID: 'XXXXXXXXXXX' })
    ).rejects.toThrow();
  }, TIMEOUT);
});

// ─── metadata format validation ───────────────────────────────────────────────

describe('getSubtitles - metadata formats', () => {
  it('publishDate is YYYY-MM-DD format or empty', () => {
    if (rickRoll.metadata.publishDate) {
      expect(rickRoll.metadata.publishDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });

  it('viewCount is a formatted string (k/M suffix) or empty', () => {
    if (rickRoll.metadata.viewCount) {
      expect(rickRoll.metadata.viewCount).toMatch(/^[\d.]+[kMB]?$/);
    }
  });

  it('adChapters is an array', () => {
    expect(Array.isArray(rickRoll.adChapters)).toBe(true);
  });
});
