import { describe, it, expect } from 'vitest';
import { getSubtitles, getAvailableLanguages } from './youtube-fetcher.js';

// Well-known stable videos with guaranteed captions
const RICK_ROLL    = 'dQw4w9WgXcQ'; // EN, auto-generated + manual
const FIRST_VIDEO  = 'jNQXAC9IVRw'; // "Me at the zoo" - short, EN captions
const TED_TALK     = 'UF8uR6Z6KLc'; // Steve Jobs Stanford 2005 - multi-language

const TIMEOUT = 30_000;

// ─── getAvailableLanguages ────────────────────────────────────────────────────

describe('getAvailableLanguages', () => {
  it('returns an array of caption tracks for a public video', async () => {
    const langs = await getAvailableLanguages(RICK_ROLL);
    expect(Array.isArray(langs)).toBe(true);
    expect(langs.length).toBeGreaterThan(0);
  }, TIMEOUT);

  it('each track has languageCode, name, isAutoGenerated', async () => {
    const langs = await getAvailableLanguages(RICK_ROLL);
    for (const track of langs) {
      expect(typeof track.languageCode).toBe('string');
      expect(track.languageCode.length).toBeGreaterThan(0);
      expect(typeof track.name).toBe('string');
      expect(typeof track.isAutoGenerated).toBe('boolean');
    }
  }, TIMEOUT);

  it('throws on empty video ID', async () => {
    await expect(getAvailableLanguages('')).rejects.toThrow();
  });

  it('throws on non-string video ID', async () => {
    // @ts-expect-error intentional bad input
    await expect(getAvailableLanguages(null)).rejects.toThrow();
  });
});

// ─── getSubtitles ─────────────────────────────────────────────────────────────

describe('getSubtitles - response shape', () => {
  it('returns all required top-level fields', async () => {
    const result = await getSubtitles({ videoID: RICK_ROLL });
    expect(result).toHaveProperty('lines');
    expect(result).toHaveProperty('requestedLang');
    expect(result).toHaveProperty('actualLang');
    expect(result).toHaveProperty('availableLanguages');
    expect(result).toHaveProperty('adChapters');
    expect(result).toHaveProperty('metadata');
  }, TIMEOUT);

  it('lines array is non-empty with valid shape', async () => {
    const { lines } = await getSubtitles({ videoID: RICK_ROLL });
    expect(lines.length).toBeGreaterThan(0);
    for (const line of lines.slice(0, 5)) {
      expect(typeof line.text).toBe('string');
      expect(line.text.length).toBeGreaterThan(0);
      expect(typeof line.start).toBe('number');
      expect(typeof line.dur).toBe('number');
      expect(line.start).toBeGreaterThanOrEqual(0);
      expect(line.dur).toBeGreaterThan(0);
    }
  }, TIMEOUT);

  it('timestamps are monotonically non-decreasing', async () => {
    const { lines } = await getSubtitles({ videoID: RICK_ROLL });
    for (let i = 1; i < lines.length; i++) {
      expect(lines[i].start).toBeGreaterThanOrEqual(lines[i - 1].start);
    }
  }, TIMEOUT);

  it('metadata has title and author', async () => {
    const { metadata } = await getSubtitles({ videoID: RICK_ROLL });
    expect(typeof metadata.title).toBe('string');
    expect(metadata.title.length).toBeGreaterThan(0);
    expect(typeof metadata.author).toBe('string');
    expect(metadata.author.length).toBeGreaterThan(0);
  }, TIMEOUT);

  it('requestedLang matches what was asked', async () => {
    const { requestedLang } = await getSubtitles({ videoID: RICK_ROLL, lang: 'en' });
    expect(requestedLang).toBe('en');
  }, TIMEOUT);
});

// ─── language handling ────────────────────────────────────────────────────────

describe('getSubtitles - language handling', () => {
  it('falls back to english when requested lang is unavailable', async () => {
    const result = await getSubtitles({ videoID: RICK_ROLL, lang: 'xx', enableFallback: true });
    expect(result.actualLang).toBe('en');
    expect(result.requestedLang).toBe('xx');
  }, TIMEOUT);

  it('throws when lang unavailable and fallback disabled', async () => {
    await expect(
      getSubtitles({ videoID: RICK_ROLL, lang: 'xx', enableFallback: false })
    ).rejects.toThrow(/not available/i);
  }, TIMEOUT);

  it('works with a short video (first YouTube video)', async () => {
    const result = await getSubtitles({ videoID: FIRST_VIDEO });
    expect(result.lines.length).toBeGreaterThan(0);
  }, TIMEOUT);
});

// ─── error handling ───────────────────────────────────────────────────────────

describe('getSubtitles - error handling', () => {
  it('throws on empty video ID', async () => {
    await expect(getSubtitles({ videoID: '' })).rejects.toThrow();
  });

  it('throws a descriptive error on a nonexistent video', async () => {
    await expect(
      getSubtitles({ videoID: 'XXXXXXXXXXX' })
    ).rejects.toThrow();
  }, TIMEOUT);
});

// ─── metadata format validation ───────────────────────────────────────────────

describe('getSubtitles - metadata formats', () => {
  it('publishDate is YYYY-MM-DD format or empty', async () => {
    const { metadata } = await getSubtitles({ videoID: RICK_ROLL });
    if (metadata.publishDate) {
      expect(metadata.publishDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  }, TIMEOUT);

  it('viewCount is a formatted string (k/M suffix) or empty', async () => {
    const { metadata } = await getSubtitles({ videoID: RICK_ROLL });
    if (metadata.viewCount) {
      expect(metadata.viewCount).toMatch(/^[\d.]+[kMB]?$/);
    }
  }, TIMEOUT);

  it('adChapters is an array', async () => {
    const { adChapters } = await getSubtitles({ videoID: RICK_ROLL });
    expect(Array.isArray(adChapters)).toBe(true);
  }, TIMEOUT);
});
